### ISSUE TITLE
Migrar módulo para Python 3

### ISSUE THREAD

**Issue by mstuttgart** [mstuttgart/pysigep#11]
Buscar manter a compatibilidade entre Python2.7 e Python3 (3.4 e 3.5)

**Comment by michelts** [comment]
Se me permitirem, posso instalar o tox no projeto, para facilitar rodar os testes em diferentes versão do python. Com isso será mais fácil migrar para py3. De acordo?

**Comment by mstuttgart** [comment]
@michelts pode sim! :+1:
