### ISSUE TITLE
Lib mais atualizada

### ISSUE THREAD

**Issue by danimaribeiro** [mstuttgart/pysigep#15]
Qual seria a lib que você recomendaria usar?

https://github.com/kmee/pySigepWeb 
ou esta?

**Comment by mstuttgart** [comment]
@danimaribeiro a do link foi feito por mim quanto ainda estava na KMEE. Ela está funcional porém não possui nenhum teste. Ela possui, além dos serviços básicos do SigepWeb, rastreamento de mercadoria e calculo de frete e foi escrita utilizando a lib *suds*. Eu trabalhei bastante tempo nela, então ela deve estar estável. 

A pysigep está coberta de testes (utiliza a lib *requests* para conversar com o servidor) porém ainda está em fase de desenvolvimento (apesar de estar funcional e ter um código melhor escrito). Ela não possui rastreamento e nem calculo de frete (os mesmo foram movidos para um módulo a parte). 

Eu recomendaria a pysigep por causa dela já possuir testes.

**Comment by danimaribeiro** [comment]
Podemos trazer o cálculo de frete e rastreio para cá? ou tem algum motivo especial para estar em módulo separado?

**Comment by mstuttgart** [comment]
O meu objetivo inicial era deixar o módulo *pysigep* responsável apenas pelos serviços do *sigepweb*, já que o rastreamento e calculo de frete não fazem parte do sigepweb (módulo com responsabilidade única). Além de também não ter de prover suporte e manutenção para esses serviços (facilitando meu trabalho). Sendo assim eu os separei.

Com exceção do motivo que destaquei acima, não vejo problema em juntá-los novamente (todos estão cobertos por testes e são escritos da mesma forma). Segue o repositório do rastreamento e do calculo de frete públicos para você dar uma olhada: https://github.com/mstuttgart/python-correios-api

**Comment by danimaribeiro** [comment]
Comecei a fazer uns testes com a lib.
Que tu acha destas mudanças?

https://github.com/danimaribeiro/pysigep/commit/f0849529d686fd4aaf25a0229379199bf072dfb1

Principalmente esta função:
https://github.com/danimaribeiro/pysigep/blob/develop/pysigep/webservices/webservice_base.py#L38
https://github.com/danimaribeiro/pysigep/blob/develop/pysigep/webservices/webservice_base.py#L75

Ela automaticamente limpa namespaces desnecessários e usa o objectify do lxml para converter em um objeto python.

Para usar o retorno:
https://github.com/Trust-Code/trustcode-addons/blob/10.0/delivery_correios/models/delivery.py#L49
https://github.com/Trust-Code/trustcode-addons/blob/10.0/delivery_correios/models/delivery.py#L90

Que tu acha também de remover algumas classes e fazer algo no estilo:
https://github.com/danimaribeiro/PyTrustNFe/blob/master/pytrustnfe/nfse/paulistana/__init__.py
Acho que fica mais fácil de manter a lib, o xml sendo gerado com o jinja permite que seja copiado direto dos exemplos do manual, não é necessário ficar criando classes com os atributos e metodos com os parametros necessários.

Se tu não achar legal, vou modificar o buscaCliente e o calcularPrecoPrazo para o formato da lib e envio um PR.

**Comment by mstuttgart** [comment]
@danimaribeiro bacana as modificações! Acredito que as mesmas sejam bem vindas!

Eu pretendia comerçar usar o *jinja* baseado justamente no trabalho que você fez na *PyTrustNFe*. Fica bem melhor criar os templates em arquivos externos *.xml*. Vamos assumir essa abordagem então.

Vi que você adicionou o serviço de frete para a lib. Acredito que o mesmo será feito com o rastremanto não? Vou estudar o código que você fez para poder te ajudar a trabalhar na refatoração da *pysigep*.

Só tenho uma dúvida quando a introduzir muito código no arquivo \__init__.py, como foi adicionado https://github.com/danimaribeiro/pysigep/commit/f0849529d686fd4aaf25a0229379199bf072dfb1. Não sei dizer se essa abordagem é recomedável em Python. Existe algum motivo em especial para o código ter sido colocado nos arquivos \__init__.py?
