### ISSUE TITLE
Instalar templates junto com o package

### ISSUE THREAD

**Issue by michelts** [mstuttgart/pysigep#18]
O pysigep não vai funcionar se eu tentar instalá-lo (por exemplo, python setup install). O modo como o setup.py foi escrito não inclue a pasta de templates.

Isto pode ser corrigido simplesmente adicionando um __init__.py na pasta de templates, para que o setuptools.find_package o inclua na listagem.

**Comment by mstuttgart** [comment]
Olá @michelts obrigado por reportar o erro!

Fixado: https://github.com/mstuttgart/pysigep/pull/19
