### ISSUE TITLE
Alterar licença/remoção de codigo

### ISSUE THREAD

**Issue by mstuttgart** [mstuttgart/pysigep#25]
@martini97 @danimaribeiro 

Vi que o código adicionado [aqui](https://github.com/mstuttgart/pysigep/blob/develop/pysigep/correios/__init__.py#L3) é AGPL.

Estou pensando em remover esse código de calculo de frete e rastreamento. Isso torna a PySIGEP mais concisa uma vez que ela irá tratar de apenas um serviço (sigepweb). Estou pensando em adicionar o código de calculo de frete e rastreamento em um modulo separado. Outro  ponto é que o código esta como AGPL. Posso alterar a licença para MIT ( a licença utilizada pelo pysigep)?

Vi também [aqui](https://github.com/mstuttgart/pysigep/blob/develop/pysigep/correios/__init__.py#L7) que existe um *header* com o *copyright* da KMEE. Ele diz respeito ao código de [sign_chancela](https://github.com/mstuttgart/pysigep/blob/develop/pysigep/correios/__init__.py#L92)?

Queria removê-lo e substitui-lo por outro código a fim de não manter código de outras lib dentro da *pysigep*

**Comment by danimaribeiro** [comment]
Por mim não tem problema em alterar a licença.

O header da Kmee é porque foi copiado de lá mesmo o método.
